# Change these first
owner: felipesbs # Your GitHub organization or username, where this repository lives
repo: bitrate-uptime # The name of this repository

sites:
  #- name: Google
  #  url: https://www.google.com
  #- name: Wikipedia
  #  url: https://en.wikipedia.org
  #- name: Hacker News
  #  url: https://news.ycombinator.com
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true
  - name: PasImpCh
    url: $SITE_PASIMPCH
    __dangerous__body_down_if_text_missing: '$SITE_STRING'
  - name: Share
    url: $SITE_SHARE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /bitrate-uptime  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bitrate Uptime
  introTitle: "**Bitrate Uptime** is proud to offer uptime monitoring and status pages, powered by state-of-the-art technology."
  introMessage: "Get your own uptime monitoring and status page for free with Bitrate. No server required, just a simple setup!"
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
